/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.10"
    id("org.jetbrains.kotlin.kapt") version "1.6.10"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.6.10"
    id("io.micronaut.application") version "3.2.1"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

micronaut {
    runtime("netty")
    testRuntime("junit5")
}

val micronautVersion: String by project
dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation(platform("io.micronaut:micronaut-bom:$micronautVersion"))
    kapt(platform("io.micronaut:micronaut-bom:$micronautVersion"))
    kapt("io.micronaut:micronaut-inject-java")
    implementation("io.micronaut.micrometer:micronaut-micrometer-core")

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")

    //RxJava3
    implementation("io.micronaut.rxjava3:micronaut-rxjava3:2.1.1")
    implementation("io.micronaut.rxjava3:micronaut-rxjava3-http-client:2.1.1")

    //Reactor
    implementation("io.micronaut.reactor:micronaut-reactor")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions:1.1.5")

    kaptTest("io.micronaut:micronaut-inject-java")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("io.micronaut.test:micronaut-test-junit5:3.0.5")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.2")

}




application {
    // Define the main class for the application.
    mainClass.set("mn.micrometer.rxjava3.AppKt")
}
