/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mn.micrometer.rxjava3

import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import jakarta.inject.Inject
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import reactor.kotlin.core.publisher.toMono

@MicronautTest
class AppTest {

    @Inject
    private lateinit var bookApiClient: BookClient


    @Test
    fun `should get a book`() {
        val book = bookApiClient.get(1).blockingGet()
        assertEquals("Test", book.title)
    }

    @Test
    fun `should get list of books`() {
        val books = bookApiClient.get().blockingIterable().toList()
        assertTrue(books.isNotEmpty())
    }

    @Test
    fun `should add a book`() {
        val book = bookApiClient.post(Book(2L, "Test2")).toMono().block()
        assertEquals(2, book?.id)
    }

    @Test
    fun `should update a book`() {
        val book = bookApiClient.put(Book(1L, "Test1")).toMono().block()
        assertEquals("Test1", book?.title)
    }

}
