/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mn.micrometer.rxjava3

import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import jakarta.inject.Inject
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

@MicronautTest
class AppTest {

    @Inject
    private lateinit var bookApiClient: BookClient


    @Test
    fun `should get a book`() {
        val book = bookApiClient.get(1).blockingGet()
        assertEquals("Test", book.title)
    }

    @Test
    fun `should get list of books`() {
        val books = bookApiClient.get().blockingFirst()
        assertEquals(1, books.size)
    }

}
